FROM python:3.9.23-trixie

WORKDIR /usr/src/app

COPY pyproject.toml ./

RUN curl -sSL https://install.python-poetry.org | python3 -

CMD ['poetry', 'install' ]

COPY . .

CMD ['poetry','run', 'uvicorn', 'app.main:app', '--host','0.0.0.0','port','8000']